<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<!-- ViewVC :: http://www.viewvc.org/ -->
<head>
<title>ViewVC Exception</title>
</head>
<body>
<h3>An Exception Has Occurred</h3>


<h4>Python Traceback</h4>
<p><pre>
Traceback (most recent call last):
  File "/usr/share/gforge/www/scm/viewvc/lib/viewvc.py", line 3612, in main
    request.run_viewvc()
  File "/usr/share/gforge/www/scm/viewvc/lib/viewvc.py", line 389, in run_viewvc
    self.view_func(self)
  File "/usr/share/gforge/www/scm/viewvc/lib/viewvc.py", line 2134, in view_checkout
    fp, revision = request.repos.openfile(path, rev)
  File "/usr/share/gforge/www/scm/viewvc/lib/vclib/svn/__init__.py", line 594, in openfile
    fp = FileContentsPipe(fsroot, path, self.pool)
  File "/usr/share/gforge/www/scm/viewvc/lib/vclib/svn/__init__.py", line 423, in __init__
    self._stream = fs.file_contents(root, path, self._pool)
  File "/usr/lib/pymodules/python2.7/libsvn/fs.py", line 627, in svn_fs_file_contents
    return _fs.svn_fs_file_contents(*args)
SubversionException: ('Attempted to get textual contents of a *non*-file node', 160017)

</pre></p>
</body>
</html>
